on: [push, pull_request]
jobs:
  develop:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: |
          make DEBUG=1 clean check all -C docs/
          make DEBUG=1 clean check all
