on: [push, pull_request, workflow_dispatch]
jobs:
  develop:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: |
          make clean check all -C docs/
          make clean check all
